#!/usr/bin/env python3
# crushon_option1.py — Selenium + Remote Debugging Port (BRAVE VERSION)
#
# Attaches to YOUR real Brave browser. Uses Visual Text Extraction
# to bypass obfuscated CSS/HTML layouts.

import argparse
import json
import logging
import time
from datetime import datetime, timezone
from pathlib import Path

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("crushon_run.log", encoding="utf-8"),
        logging.StreamHandler(),
    ]
)
log = logging.getLogger(__name__)

DEFAULT_DELAY   = 5      # seconds between messages
MESSAGE_TIMEOUT = 60     # seconds to wait for AI response to finish streaming


def connect_to_brave(port: int = 9224) -> webdriver.Chrome:
    """Attach Selenium to the already-running Brave instance."""
    options = Options()
    options.binary_location = r"C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
    options.add_experimental_option("debuggerAddress", f"127.0.0.1:{port}")
    
    try:
        service = Service(ChromeDriverManager(driver_version="147.0.7727.102").install())
        driver = webdriver.Chrome(service=service, options=options)
        log.info(f"Connected to Brave — current URL: {driver.current_url}")
        return driver
    except Exception as e:
        log.error(f"Could not connect to Brave on port {port}: {e}")
        raise


def find_chat_input(driver) -> object | None:
    """Find the message input box."""
    selectors = [
        (By.CSS_SELECTOR, "textarea[placeholder]"),
        (By.CSS_SELECTOR, "div[contenteditable='true']"),
        (By.CSS_SELECTOR, "textarea"),
    ]
    for by, selector in selectors:
        try:
            el = WebDriverWait(driver, 3).until(
                EC.presence_of_element_located((by, selector))
            )
            if el.is_displayed() and el.is_enabled():
                return el
        except TimeoutException:
            continue
    return None


def wait_and_extract_response(driver, sent_msg: str, timeout: int = 60) -> str | None:
    """
    Waits for the AI to start typing, monitors the stream until it stops, 
    and returns ONLY the text generated by the AI.
    """
    start_time = time.time()
    stable_count = 0
    prev_text = ""
    
    while time.time() - start_time < timeout:
        time.sleep(1.0)
        
        # This JS script reads the screen and specifically grabs text appearing AFTER your message
        current_text = driver.execute_script("""
            const msg = arguments[0].trim();
            // Use the last 20 characters of your message as an anchor (prevents multiline bugs)
            const anchor = msg.length > 20 ? msg.slice(-20) : msg;
            
            // Temporarily hide the text input box so it doesn't pollute the text extraction
            const inputs = document.querySelectorAll('textarea, input, [contenteditable="true"]');
            inputs.forEach(i => i.style.visibility = 'hidden');
            
            const pageText = document.body.innerText || "";
            
            // Restore visibility
            inputs.forEach(i => i.style.visibility = '');
            
            // Find where your message ends, and grab everything underneath it
            const idx = pageText.lastIndexOf(anchor);
            if (idx !== -1) {
                let after = pageText.substring(idx + anchor.length).trim();
                
                // Clean up any UI buttons that CrushOn places at the bottom of the chat
                const uiElements = ['Type a message...', 'Send', 'Regenerate', 'Reply', 'Copy'];
                let changed = true;
                while(changed && after.length > 0) {
                    changed = false;
                    for(const w of uiElements) {
                        if (after.endsWith(w)) {
                            after = after.substring(0, after.length - w.length).trim();
                            changed = true;
                        }
                    }
                }
                return after;
            }
            return "";
        """, sent_msg)
        
        # If current_text is empty, the AI is still "thinking" (hasn't started typing)
        if not current_text:
            stable_count = 0
            continue
            
        # If the text has started appearing, check if it's still growing
        if current_text == prev_text:
            stable_count += 1
            if stable_count >= 3:  # Text hasn't changed for 3 seconds = Streaming is finished!
                return current_text
        else:
            stable_count = 0  # Text is still growing, reset the timer
            
        prev_text = current_text
        
    return prev_text if prev_text else None


def send_messages(driver, messages: list[str], delay: int = DEFAULT_DELAY) -> list[dict]:
    results = []

    for i, message in enumerate(messages):
        log.info(f"[{i+1}/{len(messages)}] Sending: {message[:60]}...")

        chat_input = find_chat_input(driver)
        if chat_input is None:
            log.error("Could not find chat input — stopping")
            break

        # Send the message
        chat_input.click()
        time.sleep(0.3)
        chat_input.send_keys(Keys.CONTROL + "a")
        time.sleep(0.1)
        chat_input.send_keys(message)
        time.sleep(0.5)
        chat_input.send_keys(Keys.RETURN)
        
        send_time = datetime.now(timezone.utc).isoformat()
        
        log.info("  Waiting for AI to think and stream response...")
        
        # Wait for the AI to finish and extract the exact text
        response_text = wait_and_extract_response(driver, message, timeout=MESSAGE_TIMEOUT)

        result = {
            "index": i + 1,
            "message": message,
            "response": response_text,
            "timestamp": send_time,
            "platform": "crushon.ai",
            "approach": "selenium_remote_debug",
            "status": "success" if response_text else "timeout",
        }
        results.append(result)

        if response_text:
            # Print the first 80 characters so you can see it working in the console
            preview = response_text.replace('\n', ' ')
            log.info(f"  Response captured: {preview[:80]}...")
        else:
            log.warning(f"  No response captured for message {i+1}")

        if i < len(messages) - 1:
            time.sleep(delay)

    return results


def load_messages(messages_arg: list[str]) -> list[str]:
    if len(messages_arg) == 1 and Path(messages_arg[0]).exists():
        p = Path(messages_arg[0])
        if p.suffix == ".json":
            return json.loads(p.read_text())
        return [l.strip() for l in p.read_text().splitlines() if l.strip()]
    return messages_arg


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--messages", nargs="+", required=True)
    parser.add_argument("--output", default="results.json")
    parser.add_argument("--port", type=int, default=9224)
    parser.add_argument("--delay", type=int, default=DEFAULT_DELAY)
    args = parser.parse_args()

    messages = load_messages(args.messages)
    log.info(f"Loaded {len(messages)} messages")
    
    driver = connect_to_brave(args.port)

    if "crushon.ai" not in driver.current_url:
        log.warning("Brave is not on crushon.ai — navigate to your character's chat page first")
        driver.quit()
        return

    results = send_messages(driver, messages, args.delay)

    # Save output
    output = {
        "metadata": {
            "platform": "crushon.ai",
            "total": len(messages),
            "successful": sum(1 for r in results if r["status"] == "success"),
            "run_at": datetime.now(timezone.utc).isoformat(),
        },
        "results": results,
    }
    Path(args.output).write_text(json.dumps(output, indent=2, ensure_ascii=False))

    log.info(f"\nDone — {output['metadata']['successful']}/{len(messages)} successful")
    print("\n--- SUMMARY ---")
    for r in results:
        status = "✓" if r["status"] == "success" else "✗"
        msg = r["message"][:40].ljust(40)
        resp = str(r.get("response", "NO RESPONSE"))[:55].replace('\n', ' ')
        print(f"{status} [{r['index']:>2}] {msg} → {resp}")


if __name__ == "__main__":
    main()